knp_paginator:
    page_range: 5                       # number of links shown in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: field  # filter field query parameter name
        filter_value_name: q  # filter value query parameter name
    template:
        pagination: 'knp_paginator/pagination.html.twig'     # sliding pagination controls template
        sortable: 'knp_paginator/sortable.html.twig' # sort link template
        filtration: 'knp_paginator/filter.html.twig'  # filters template