controllers:
    resource: ../src/
    type: attribute

api:
    resource: ../src/Api/
    type: attribute

logout:
    path: /logout
    methods: GET

profile:
    path: /{slug} # slug of user
    controller: App\Authentication\Controller\ProfileController::index
    methods: GET

api_login_check:
    path: /api/login_check