controllers:
    resource: ../src/
    type: attribute

api:
    resource: ../src/Api/
    type: attribute
    prefix: /api

api_login_check:
    path: /api/login_check
    methods: ['POST']

api_index:
    path: /api
    controller: App\Api\Controller\AssetApiController::index

logout:
    path: /logout
    methods: GET

profile:
    path: /{slug} # slug of user
    controller: App\Authentication\Controller\ProfileController::index
    methods: GET