controllers:
    resource: ../src/
    type: attribute

logout:
    path: /logout
    methods: GET

profile:
    path: /{slug}
    controller: App\Authentication\Controller\ProfileController::index
    methods: GET